# Generated by Django 3.2 on 2024-03-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20240331_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='buisness_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
