# Generated by Django 3.2 on 2024-04-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_auto_20240401_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='channel.community'),
        ),
    ]
